// Generated by gencpp from file agar_navigation/RobotSpeedSave.msg
// DO NOT EDIT!


#ifndef AGAR_NAVIGATION_MESSAGE_ROBOTSPEEDSAVE_H
#define AGAR_NAVIGATION_MESSAGE_ROBOTSPEEDSAVE_H

#include <ros/service_traits.h>


#include <agar_navigation/RobotSpeedSaveRequest.h>
#include <agar_navigation/RobotSpeedSaveResponse.h>


namespace agar_navigation
{

struct RobotSpeedSave
{

typedef RobotSpeedSaveRequest Request;
typedef RobotSpeedSaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotSpeedSave
} // namespace agar_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agar_navigation::RobotSpeedSave > {
  static const char* value()
  {
    return "eaee30a82966f2d54c874e2a0ce23a9b";
  }

  static const char* value(const ::agar_navigation::RobotSpeedSave&) { return value(); }
};

template<>
struct DataType< ::agar_navigation::RobotSpeedSave > {
  static const char* value()
  {
    return "agar_navigation/RobotSpeedSave";
  }

  static const char* value(const ::agar_navigation::RobotSpeedSave&) { return value(); }
};


// service_traits::MD5Sum< ::agar_navigation::RobotSpeedSaveRequest> should match
// service_traits::MD5Sum< ::agar_navigation::RobotSpeedSave >
template<>
struct MD5Sum< ::agar_navigation::RobotSpeedSaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agar_navigation::RobotSpeedSave >::value();
  }
  static const char* value(const ::agar_navigation::RobotSpeedSaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agar_navigation::RobotSpeedSaveRequest> should match
// service_traits::DataType< ::agar_navigation::RobotSpeedSave >
template<>
struct DataType< ::agar_navigation::RobotSpeedSaveRequest>
{
  static const char* value()
  {
    return DataType< ::agar_navigation::RobotSpeedSave >::value();
  }
  static const char* value(const ::agar_navigation::RobotSpeedSaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agar_navigation::RobotSpeedSaveResponse> should match
// service_traits::MD5Sum< ::agar_navigation::RobotSpeedSave >
template<>
struct MD5Sum< ::agar_navigation::RobotSpeedSaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agar_navigation::RobotSpeedSave >::value();
  }
  static const char* value(const ::agar_navigation::RobotSpeedSaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agar_navigation::RobotSpeedSaveResponse> should match
// service_traits::DataType< ::agar_navigation::RobotSpeedSave >
template<>
struct DataType< ::agar_navigation::RobotSpeedSaveResponse>
{
  static const char* value()
  {
    return DataType< ::agar_navigation::RobotSpeedSave >::value();
  }
  static const char* value(const ::agar_navigation::RobotSpeedSaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGAR_NAVIGATION_MESSAGE_ROBOTSPEEDSAVE_H
