// Generated by gencpp from file agar_navigation/RobotStatusSrvRequest.msg
// DO NOT EDIT!


#ifndef AGAR_NAVIGATION_MESSAGE_ROBOTSTATUSSRVREQUEST_H
#define AGAR_NAVIGATION_MESSAGE_ROBOTSTATUSSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agar_navigation
{
template <class ContainerAllocator>
struct RobotStatusSrvRequest_
{
  typedef RobotStatusSrvRequest_<ContainerAllocator> Type;

  RobotStatusSrvRequest_()
    {
    }
  RobotStatusSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatusSrvRequest_

typedef ::agar_navigation::RobotStatusSrvRequest_<std::allocator<void> > RobotStatusSrvRequest;

typedef boost::shared_ptr< ::agar_navigation::RobotStatusSrvRequest > RobotStatusSrvRequestPtr;
typedef boost::shared_ptr< ::agar_navigation::RobotStatusSrvRequest const> RobotStatusSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace agar_navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agar_navigation/RobotStatusSrvRequest";
  }

  static const char* value(const ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatusSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::agar_navigation::RobotStatusSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AGAR_NAVIGATION_MESSAGE_ROBOTSTATUSSRVREQUEST_H
