// Generated by gencpp from file agar_navigation/RobotStatusSrv.msg
// DO NOT EDIT!


#ifndef AGAR_NAVIGATION_MESSAGE_ROBOTSTATUSSRV_H
#define AGAR_NAVIGATION_MESSAGE_ROBOTSTATUSSRV_H

#include <ros/service_traits.h>


#include <agar_navigation/RobotStatusSrvRequest.h>
#include <agar_navigation/RobotStatusSrvResponse.h>


namespace agar_navigation
{

struct RobotStatusSrv
{

typedef RobotStatusSrvRequest Request;
typedef RobotStatusSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RobotStatusSrv
} // namespace agar_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agar_navigation::RobotStatusSrv > {
  static const char* value()
  {
    return "a31bc4a504f5eb9e3c4b51e387fba977";
  }

  static const char* value(const ::agar_navigation::RobotStatusSrv&) { return value(); }
};

template<>
struct DataType< ::agar_navigation::RobotStatusSrv > {
  static const char* value()
  {
    return "agar_navigation/RobotStatusSrv";
  }

  static const char* value(const ::agar_navigation::RobotStatusSrv&) { return value(); }
};


// service_traits::MD5Sum< ::agar_navigation::RobotStatusSrvRequest> should match
// service_traits::MD5Sum< ::agar_navigation::RobotStatusSrv >
template<>
struct MD5Sum< ::agar_navigation::RobotStatusSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agar_navigation::RobotStatusSrv >::value();
  }
  static const char* value(const ::agar_navigation::RobotStatusSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agar_navigation::RobotStatusSrvRequest> should match
// service_traits::DataType< ::agar_navigation::RobotStatusSrv >
template<>
struct DataType< ::agar_navigation::RobotStatusSrvRequest>
{
  static const char* value()
  {
    return DataType< ::agar_navigation::RobotStatusSrv >::value();
  }
  static const char* value(const ::agar_navigation::RobotStatusSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agar_navigation::RobotStatusSrvResponse> should match
// service_traits::MD5Sum< ::agar_navigation::RobotStatusSrv >
template<>
struct MD5Sum< ::agar_navigation::RobotStatusSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agar_navigation::RobotStatusSrv >::value();
  }
  static const char* value(const ::agar_navigation::RobotStatusSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agar_navigation::RobotStatusSrvResponse> should match
// service_traits::DataType< ::agar_navigation::RobotStatusSrv >
template<>
struct DataType< ::agar_navigation::RobotStatusSrvResponse>
{
  static const char* value()
  {
    return DataType< ::agar_navigation::RobotStatusSrv >::value();
  }
  static const char* value(const ::agar_navigation::RobotStatusSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGAR_NAVIGATION_MESSAGE_ROBOTSTATUSSRV_H
