(cl:defpackage agar_navigation-srv
  (:use )
  (:export
   "AGARPARAMS"
   "<AGARPARAMS-REQUEST>"
   "AGARPARAMS-REQUEST"
   "<AGARPARAMS-RESPONSE>"
   "AGARPARAMS-RESPONSE"
   "AUTOMOVESAVE"
   "<AUTOMOVESAVE-REQUEST>"
   "AUTOMOVESAVE-REQUEST"
   "<AUTOMOVESAVE-RESPONSE>"
   "AUTOMOVESAVE-RESPONSE"
   "ROBOTSPEEDSAVE"
   "<ROBOTSPEEDSAVE-REQUEST>"
   "ROBOTSPEEDSAVE-REQUEST"
   "<ROBOTSPEEDSAVE-RESPONSE>"
   "ROBOTSPEEDSAVE-RESPONSE"
   "ROBOTSTATUSSRV"
   "<ROBOTSTATUSSRV-REQUEST>"
   "ROBOTSTATUSSRV-REQUEST"
   "<ROBOTSTATUSSRV-RESPONSE>"
   "ROBOTSTATUSSRV-RESPONSE"
  ))

