// Generated by gencpp from file reach_rs_driver/GpsStatusSrv.msg
// DO NOT EDIT!


#ifndef REACH_RS_DRIVER_MESSAGE_GPSSTATUSSRV_H
#define REACH_RS_DRIVER_MESSAGE_GPSSTATUSSRV_H

#include <ros/service_traits.h>


#include <reach_rs_driver/GpsStatusSrvRequest.h>
#include <reach_rs_driver/GpsStatusSrvResponse.h>


namespace reach_rs_driver
{

struct GpsStatusSrv
{

typedef GpsStatusSrvRequest Request;
typedef GpsStatusSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GpsStatusSrv
} // namespace reach_rs_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reach_rs_driver::GpsStatusSrv > {
  static const char* value()
  {
    return "1a4db83181fcb1e5355d5efa1e2f87a9";
  }

  static const char* value(const ::reach_rs_driver::GpsStatusSrv&) { return value(); }
};

template<>
struct DataType< ::reach_rs_driver::GpsStatusSrv > {
  static const char* value()
  {
    return "reach_rs_driver/GpsStatusSrv";
  }

  static const char* value(const ::reach_rs_driver::GpsStatusSrv&) { return value(); }
};


// service_traits::MD5Sum< ::reach_rs_driver::GpsStatusSrvRequest> should match
// service_traits::MD5Sum< ::reach_rs_driver::GpsStatusSrv >
template<>
struct MD5Sum< ::reach_rs_driver::GpsStatusSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reach_rs_driver::GpsStatusSrv >::value();
  }
  static const char* value(const ::reach_rs_driver::GpsStatusSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reach_rs_driver::GpsStatusSrvRequest> should match
// service_traits::DataType< ::reach_rs_driver::GpsStatusSrv >
template<>
struct DataType< ::reach_rs_driver::GpsStatusSrvRequest>
{
  static const char* value()
  {
    return DataType< ::reach_rs_driver::GpsStatusSrv >::value();
  }
  static const char* value(const ::reach_rs_driver::GpsStatusSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reach_rs_driver::GpsStatusSrvResponse> should match
// service_traits::MD5Sum< ::reach_rs_driver::GpsStatusSrv >
template<>
struct MD5Sum< ::reach_rs_driver::GpsStatusSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reach_rs_driver::GpsStatusSrv >::value();
  }
  static const char* value(const ::reach_rs_driver::GpsStatusSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reach_rs_driver::GpsStatusSrvResponse> should match
// service_traits::DataType< ::reach_rs_driver::GpsStatusSrv >
template<>
struct DataType< ::reach_rs_driver::GpsStatusSrvResponse>
{
  static const char* value()
  {
    return DataType< ::reach_rs_driver::GpsStatusSrv >::value();
  }
  static const char* value(const ::reach_rs_driver::GpsStatusSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REACH_RS_DRIVER_MESSAGE_GPSSTATUSSRV_H
