// Generated by gencpp from file reach_rs_driver/GpsStatusSrvRequest.msg
// DO NOT EDIT!


#ifndef REACH_RS_DRIVER_MESSAGE_GPSSTATUSSRVREQUEST_H
#define REACH_RS_DRIVER_MESSAGE_GPSSTATUSSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reach_rs_driver
{
template <class ContainerAllocator>
struct GpsStatusSrvRequest_
{
  typedef GpsStatusSrvRequest_<ContainerAllocator> Type;

  GpsStatusSrvRequest_()
    {
    }
  GpsStatusSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GpsStatusSrvRequest_

typedef ::reach_rs_driver::GpsStatusSrvRequest_<std::allocator<void> > GpsStatusSrvRequest;

typedef boost::shared_ptr< ::reach_rs_driver::GpsStatusSrvRequest > GpsStatusSrvRequestPtr;
typedef boost::shared_ptr< ::reach_rs_driver::GpsStatusSrvRequest const> GpsStatusSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace reach_rs_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reach_rs_driver/GpsStatusSrvRequest";
  }

  static const char* value(const ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsStatusSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::reach_rs_driver::GpsStatusSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // REACH_RS_DRIVER_MESSAGE_GPSSTATUSSRVREQUEST_H
